name: GitHub Actions - Workflow run Super Combinado Template

on:
  workflow_run:
    workflows: ["GitHub Actions - Trigger"]
    types: [requested, in_progress, completed]

jobs:
  super_job:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow super combinado executando
        run: echo "Workflow Run Super Combinado executado"
